packages:
  - package
  - tests

autoInstallPeers: true

enablePrePostScripts: true

legacyPeerDeps: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - pnpm

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver

overrides:
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'

strictPeerDependencies: false
