packages:
  - package
  - tests

autoInstallPeers: true

enablePrePostScripts: true

legacyPeerDeps: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - pnpm

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver

overrides:
  js-yaml@<4.1.1: '>=4.1.1'
  '@eslint/js': ^9
  eslint: ^9
  '@stylistic/eslint-plugin': '>=5.0.0'

strictPeerDependencies: false
