packages:
  - package
  - tests

autoInstallPeers: true

enablePrePostScripts: true

legacyPeerDeps: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - pnpm

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver

overrides:
  file-type@>=13.0.0 <21.3.1: '>=21.3.1'
  minimatch@<10.2.1: '>=10.2.1'

strictPeerDependencies: false
