packages:
  - package
  - tests

autoInstallPeers: true

enablePrePostScripts: true

legacyPeerDeps: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - pnpm

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver

overrides:
  '@eslint/eslintrc>ajv': ^6.12.4
  '@eslint/eslintrc>minimatch': ^3.1.2
  '@eslint/js': '>=10'
  '@stylistic/eslint-plugin': '>=5.0.0'
  ajv@<6.14.0: '>=6.14.0'
  ajv@<8.18.0: '>=8.18.0'
  eslint: '>=10'
  eslint>ajv: ^6.12.4
  js-yaml@<4.1.1: '>=4.1.1'
  minimatch@<10.2.1: '>=10.2.1'

strictPeerDependencies: false
